name: NSIS Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      image-path: 'https://nsis.sourceforge.io/mediawiki/images/'
    
    steps:
      - uses: actions/checkout@v2

      - uses: carlosperate/download-file-action@v1.1.1
        id: logex
        with:
          file-url: '${{ image-path }}d/d1/LogEx.zip'

      - run: 7z x -o"nsis_plugins" "${{ steps.logex.outputs.file-path }}"