name: NSIS Workflow

on:
  push:
    branches: [ main, workflows ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: carlosperate/download-file-action@v1.1.1
        id: logex
        with:
          file-url: 'https://nsis.sourceforge.io/mediawiki/images/d/d1/LogEx.zip'

      - run: 7z e -o"nsis_plugins" "${{ steps.logex.outputs.file-path }}" Plugins/*.dll -y

      - uses: carlosperate/download-file-action@v1.1.1
        id: nsisunz
        with:
          file-url: 'https://nsis.sourceforge.io/mediawiki/images/1/1c/Nsisunz.zip'

      - run: 7z e -o"nsis_plugins" "${{ steps.nsisunz.outputs.file-path }}" *.dll -r -y

      - uses: carlosperate/download-file-action@v1.1.1
        id: nscurl
        with:
          file-url: 'https://github.com/negrutiu/nsis-nscurl/releases/download/v1.2022.6.7/NScurl-1.2022.6.7.7z'

      - run: 7z e -o"nsis_plugins" "${{ steps.nscurl.outputs.file-path }}" x86-unicode/*.dll -y

      - uses: carlosperate/download-file-action@v1.1.1
        id: nsprocess
        with:
          file-url: 'https://nsis.sourceforge.io/mediawiki/images/1/18/NsProcess.zip'

      - run: 7z e -o"nsis_plugins" "${{ steps.nsprocess.outputs.file-path }}" Plugin/*.dll -y

      - uses: carlosperate/download-file-action@v1.1.1
        id: titlebar
        with:
          file-url: 'https://nsis.sourceforge.io/mediawiki/images/f/fc/TitlebarProgress.zip'

      - run: 7z e -o"nsis_plugins" "${{ steps.titlebar.outputs.file-path }}" *.dll -y

      - uses: carlosperate/download-file-action@v1.1.1
        id: taskbar
        with:
          file-url: 'https://nsis.sourceforge.io/mediawiki/images/6/6f/Win7TaskbarProgress_20091109.zip'

      - run: 7z e -o"nsis_plugins" "${{ steps.taskbar.outputs.file-path }}" *.dll -y

      - run: dir nsis_plugins